language: node_js
node_js:
  - "12.18.3"
cache: npm

sudo: required

services:
  - docker
notifications:
  email: false

before_install:
  - sudo apt-get install libsecret-1-dev

jobs:
  include:
      - stage: tests
        name: "Unit tests"
        script:
          - echo 'npm ci:' && echo -en 'travis_fold:start:script.1\\r'
          - npm ci
          - echo -en 'travis_fold:end:script.1\\r'

          - docker-compose up -d graph-node
          - ./wait-for-it.sh 127.0.0.1:8545
          - ./wait-for-it.sh 127.0.0.1:8000
          - ./wait-for-it.sh 127.0.0.1:8020

          - echo 'Debug info:' && echo -en 'travis_fold:start:script.3\\r'
          - docker-compose logs ganache
          - docker-compose logs graph-node
          - echo -en 'travis_fold:end:script.3\\r'
          - echo -en 'travis_fold:end:script.2\\r'
          - ./wait-for-subgraph.sh
          - npm run test

      - stage: tests
        name: "ts/es Lint"
        script: npm run lint

      - stage: coverage
        name: "Test Coverage"
        if: branch = master-2
        script:
          - npm run report-coverage

after_success:
  # - npm run report-coverage
  # - test $TRAVIS_BRANCH = "master" && npm run deploy-docs
  # - test $TRAVIS_BRANCH = "master" && npm run semantic-release
