language: node_js
node_js:
  - "12.18.3"
cache: npm

sudo: required

services:
  - docker
notifications:
  email: false

before_install:
  - sudo apt-get install libsecret-1-dev

jobs:
  include:
      - stage: tests
        name: "Unit tests"
        script:
          - ./scripts/travis-prepare.sh
          - npm run test

      - stage: tests
        name: "ts/es Lint"
        script: npm run lint

      - stage: coverage
        name: "Test Coverage"
        if: branch = master-2
        script:
          - ./scripts/travis-prepare.sh
          - npm run report-coverage

after_success:
  # - npm run report-coverage
  # - test $TRAVIS_BRANCH = "master" && npm run deploy-docs
  # - test $TRAVIS_BRANCH = "master" && npm run semantic-release
